openapi: 3.0.3
info:
  title: Cepheid API
  description: |-
    Base Cepheid API Definition
  contact:
    email: kevin@shapley.io
  version: 0.0.1
servers:
  - url: https://cepheid.shapley.io
  - url: https://cepheid.stg.shapley.io
  - url: http://localhost:8080
  - url: http://127.0.0.1:8080
tags:
  - name: Feature Flags
    description: Operations around managing Feature Flags
paths:
  /feature_flag/{id}:
    get:
      tags:
        - Feature Flags
      summary: Gets a Feature Flag By Id
      description: Gets a Feature Flag By Id
      operationId: getFeatureFlag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Found Feature Flag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFlagWithId'
    put:
      tags:
        - Feature Flags
      summary: Update a Feature Flag By Id
      description: Update a Feature Flag By Id
      operationId: updateFeatureFlag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: "A feature flag configuration"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatureFlag'
      responses:
        '200':
          description: Found Feature Flag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFlagWithId'
    delete:
      tags:
        - Feature Flags
      summary: Deletes a Feature Flag By Id
      description: Deletes a Feature Flag By Id
      operationId: deleteFeatureFlag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully Deleted a Feature Flag
      # security:
      #   - OAuth2:
      #     - featureflags:read
  /feature_flag:
    post:
      tags:
        - Feature Flags
      summary: Create a Feature Flag
      description: Create a Feature Flag
      operationId: createFeatureFlag
      requestBody:
        description: "A feature flag configuration"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatureFlag'
      responses:
        '200':
          description: Found Feature Flag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFlagWithId'
      

components:
  schemas:
    FeatureFlag:
      type: object
      properties:
        name:
          type: string
        value:
          type: boolean
    FeatureFlagWithId:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        value:
          type: boolean
  
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sso.shapley.io/oauth2/auth
          tokenUrl: https://sso.shapley.io/oauth2/token
          scopes:
            featureflags:read: Ability to Read Feature Flags
    APIKey:
      type: apiKey
      name: api_key
      in: header